// GitHub-inspired light syntax theme for react-syntax-highlighter
export const lightTheme = {
  'code[class*="language-"]': {
    color: '#1f2328',
    fontFamily: 'var(--font-mono)',
    fontSize: '13px',
    lineHeight: '1.65',
    direction: 'ltr',
    textAlign: 'left',
    whiteSpace: 'pre',
    wordSpacing: 'normal',
    wordBreak: 'normal',
    tabSize: '2',
    hyphens: 'none',
    background: 'transparent',
  },
  'pre[class*="language-"]': {
    color: '#1f2328',
    fontFamily: 'var(--font-mono)',
    fontSize: '13px',
    lineHeight: '1.65',
    margin: '0',
    padding: '14px 16px',
    overflow: 'auto',
    background: 'var(--code-bg)',
  },
  comment:              { color: '#6a737d', fontStyle: 'italic' },
  prolog:               { color: '#6a737d' },
  doctype:              { color: '#6a737d' },
  cdata:                { color: '#6a737d' },
  punctuation:          { color: '#5c6370' },
  'namespace':          { opacity: '0.7' },
  property:             { color: '#0550ae' },
  tag:                  { color: '#116329' },
  boolean:              { color: '#0550ae' },
  number:               { color: '#0550ae' },
  constant:             { color: '#0550ae' },
  symbol:               { color: '#0550ae' },
  deleted:              { color: '#82071e', background: '#ffebe9' },
  selector:             { color: '#8250df' },
  'attr-name':          { color: '#0550ae' },
  string:               { color: '#0a3069' },
  char:                 { color: '#0a3069' },
  builtin:              { color: '#6639ba' },
  inserted:             { color: '#116329', background: '#dafbe1' },
  entity:               { color: '#0a3069', cursor: 'help' },
  atrule:               { color: '#cf222e' },
  'attr-value':         { color: '#0a3069' },
  keyword:              { color: '#cf222e', fontWeight: '500' },
  function:             { color: '#6639ba' },
  'class-name':         { color: '#953800', fontWeight: '500' },
  regex:                { color: '#0a3069' },
  important:            { color: '#cf222e', fontWeight: 'bold' },
  variable:             { color: '#116329' },
  bold:                 { fontWeight: 'bold' },
  italic:               { fontStyle: 'italic' },
  operator:             { color: '#cf222e' },
  'maybe-class-name':   { color: '#953800' },
  parameter:            { color: '#1f2328' },
  'template-string':    { color: '#0a3069' },
  'template-punctuation':{ color: '#0550ae' },
  'literal-property':   { color: '#1f2328' },
}
